name: Bug Report - Vue 3
description: 'Submit a Vue 3 related issue.'
labels: ['vue 3']
body:
  - type: markdown
    attributes:
      value: |
        Please read [our full contribution guide](https://laravel.com/docs/contributions#bug-reports) before submitting bug reports.

        Before submitting, please confirm:
        - The issue is reproducible with the **latest version** of Inertia.js
        - You are using **supported versions** of Node.js, PHP, and other server-side dependencies
  - type: input
    attributes:
      label: '@inertiajs/vue3 Version'
      description: Provide the version of `@inertiajs/vue3` you are using.
      placeholder: 2.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Backend stack (optional)
      description: If this bug depends on backend integration, provide details such as Laravel version, PHP version, or other relevant environment info.
      placeholder: |
        Laravel 12.x
        PHP 8.4
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the problem
      description: Explain the behavior you're seeing that you think is a bug, and describe how you expect it to behave instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue. Include a minimal code example that clearly shows the problem.
    validations:
      required: true
