name: Bug Report
description: "Submit an issue."
body:
  - type: markdown
    attributes:
      value: "Please read [our full contribution guide](https://laravel.com/docs/contributions#bug-reports) before submitting bug reports."
  - type: checkboxes
    attributes:
      label: Inertia Adapter(s) Affected
      description: Select all frontend adapters that are impacted by this issue.
      options:
        - label: React
        - label: Vue
        - label: Svelte
        - label: Not Applicable
  - type: input
    attributes:
      label: "@inertiajs/... Version"
      description: Provide the version of `@inertiajs/...` you are using.
      placeholder: 2.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Backend Stack (optional)
      description: If this bug depends on backend integration, provide details such as Laravel version, PHP version, or other relevant environment info.
      placeholder: |
        Laravel 12.x
        PHP 8.4
      value: " "
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the problem
      description: Explain the behavior you're seeing that you think is a bug, and describe how you expect it to behave instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue. Include a minimal code example that clearly shows the problem.
    validations:
      required: true
