name: Playwright Tests on WebKit
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-webkit:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    name: WebKit (${{ matrix.adapter }} - shard ${{ matrix.shard }} of 4)
    timeout-minutes: 15
    runs-on: macos-15
    strategy:
      matrix:
        adapter: ['vue', 'react', 'svelte']
        shard: ['1', '2', '3', '4']
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.1.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Inertia
        run: pnpm -r --filter './packages/{core,vite}' --filter './packages/${{ matrix.adapter }}*' build

      - name: Get Playwright Version
        id: playwright-version
        run: echo "version=$(node -e "console.log(require('playwright/package.json').version)")" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: playwright-cache
        with:
          path: ~/Library/Caches/ms-playwright
          key: playwright-${{ runner.os }}-webkit-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps webkit

      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps webkit

      - name: Run Playwright Tests
        run: pnpm test:${{ matrix.adapter }} --webkit --shard=${{ matrix.shard }}/4

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: playwright-failure-screenshots-${{ matrix.adapter }}-webkit-shard-${{ matrix.shard }}
          path: test-results
