name: Publish Packages

on:
  release:
    types: [released, prereleased]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        adapter: ['core', 'vue3', 'react', 'svelte', 'vite']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 11.1.1

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit dependencies
        run: pnpm audit

      - name: 'Publish ${{ matrix.adapter }}'
        run: pnpm -r --filter ./packages/core --filter ./packages/${{ matrix.adapter }} build

      - name: Determine npm tag
        id: tag
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "flag=--tag beta" >> $GITHUB_OUTPUT
          else
            echo "flag=" >> $GITHUB_OUTPUT
          fi

      - name: 'Publish ${{ matrix.adapter }} to npm'
        run: cd ./packages/${{ matrix.adapter }} && pnpm publish --no-git-checks ${{ steps.tag.outputs.flag }}
